admin_app/urls.py
from django.urls import path
from .views import superuser_login, admin_page, index_page, vendor_details, remove_vendor, approve_vendor, order_page_admin, user_details, remove_user, feedback_page, admin_food_items, move_train

app_name = 'admin_app'

urlpatterns = [
    path('', index_page, name='index_page'),
    path('superuser/login/', superuser_login, name='superuser_login'),
    path('admin_page/', admin_page, name='admin_page'),
    path('vendor_details/', vendor_details, name='vendor_details'),
    path('remove_vendor/<int:id>', remove_vendor, name='remove_vendor'),
    path('approve_vendor/', approve_vendor, name='approve_vendor'),
    path('order_page_admin/', order_page_admin, name='order_page_admin'),
    path('user_details/', user_details, name='user_details'),
    path('remove_user/<int:id>/', remove_user, name='remove_user'),
    path('feedback_page/', feedback_page, name='feedback_page'),
    path('admin_food_items/', admin_food_items, name='admin_food_items'),
    path('admin_food_items/', admin_food_items, name='admin_food_items'),
    path('move_train/', move_train, name='move_train')
]

food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vendor_app.urls')),
    path('', include('admin_app.urls')),
    path('', include('user_app.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from .views import user_registraion, user_page, login_page_user, order_page, order_page_remove_item, feedback_by_user, payment, display_pnr
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user_app'

urlpatterns = [
    path('user_registration/', user_registraion, name='user_registration'),
    path('user_page/', user_page, name='user_page'),
    path('login_page_user/', login_page_user, name='login_page_user'),
    path('order_page/', order_page, name='order_page'),
    path('order_page_remove_item/<int:id>', order_page_remove_item, name='order_page_remove_item'),
    path('feedback_by_user/', feedback_by_user, name='feedback_by_user'),
    path('payment_page/',  payment, name='payment_page'),
    path('display_pnr/', display_pnr, name='display_pnr'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendor_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'vendor_app'

urlpatterns = [
    path('vendor_reg/', views.vendor_registration_view, name='vendor_reg'),
    path('vendor_page/', views.vendor_home_page, name='vendor_page'),
    path('delete_product/<int:id>', views.delete_product, name='delete_product'),
    path('login_page/', views.login_page, name='login_page'),
    path('add_food/', views.add_food, name='add_food'),
    path('update_food/<int:id>', views.update_food, name='update_food'),
    path('updated_food/', views.updated_food, name='updated_food'),
    path('order_page_vendor/', views.order_page_vendor, name='order_page_vendor'),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_food.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add New Food</title>

    <style>
      body {
        margin: 0px;
        padding: 0px;
        box-sizing: border-box;
      }
      .add-food-container {
        height: 100vh;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
      }
      .add-food-container form .add-food {
        display: flex;
        flex-direction: column;
        justify-content: center;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.15);
        padding: 40px 60px;
      }
      .add-food-container form .add-food input {
        margin-bottom: 25px;
        padding: 10px 10px;
        font-size: 16px;
        width: 93%;
        outline: none;
      }
      .add-food-container form .add-food label {
        font-size: 16px;
        margin-bottom: 4px;
      }

      .add-food-container form .add-food h1 {
        font-size: 2.5rem;
        text-align: center;
        margin-bottom: 2rem;
      }
      .add-food-container form .add-food button {
        padding: 10px 50px;
        width: 100%;
        background: orange;
        color: black;
        cursor: pointer;
        border: none;
        border-radius: 3px;
        font-size: 16px;
        margin-bottom: 10px;
      }
      .add-food-container form .add-food select {
        margin-bottom: 25px;
        padding: 10px 10px;
        font-size: 16px;
        width: 100%;
        outline: none;
      }
      .add-food-container form .add-food .message {
        color: red;
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <div class="add-food-container">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="add-food">
          <h1>Add Food</h1>

          <label>Food Name: </label>
          <input
            type="text"
            placeholder="Food Name"
            name="food_name"
            required
          />
          <label>Food Category: </label>
          <input
            type="text"
            placeholder="Food Category"
            name="food_category"
            maxlength="20"
            required
          />
          <label>Food Price: </label>
          <input
            type="number"
            placeholder="Food Price"
            name="food_price"
            required
          />
          <label>Resturant Name: </label>
          <input
            type="text"
            placeholder="Resturant Name"
            name="resturant_name"
            required
          />
          <label>Station: </label>
          <select name="station_name" required>
            <option value="ernakulam">Ernakulam</option>
            <option value="kollam">Kollam</option>
            <option value="trivandrum">Trivandrum</option>
          </select>

          <label style="margin-top: 3rem">Food Image: </label>
          <input type="file" name="food_image" required />

          <button type="submit">ADD</button>
          <p><a href="{% url 'vendor_app:vendor_page' %}">Return Home</a></p>
          <p class="message">{% for i in messages %} {{i}} {% endfor %}</p>
        </div>
      </form>
    </div>
  </body>
</html>

templates/admin_approve_vendor.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VENDOR APPROVAL</title>
    <style>
      body {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }
      .vendor-approval-table {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
        width: 100vw;
        height: 100vh;
        display: flex;
        align-items: start;
        justify-content: center;
      }

      .vendor-approval-table nav {
        position: fixed;
        top: 0;
      }
      .vendor-approval-table nav .nav {
        width: 100vw;
        height: 80px;
        background: rgb(228, 226, 226);
        display: flex;
        align-items: center;
        justify-content: start;
      }
      .vendor-approval-table nav a {
        color: rgb(3, 10, 102);
        margin-left: 10px;
        text-decoration: none;
        font-weight: bold;
        font-size: 16px;
        margin-right: 1rem;
      }
      .vendor-approval-table .content-table {
        border-collapse: collapse;
        margin-top: 8rem;
        width: 50%;
        font-size: 1.3rem;
        border-radius: 5px 5px 0 0;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
      }
      .vendor-approval-table .content-table thead tr {
        background-color: #009879;
        color: #fff;
        text-align: left;
        font-weight: bold;
      }
      .vendor-approval-table .content-table thead tr th,
      .vendor-approval-table .content-table tbody tr td {
        padding: 12px 15px;
      }
      .vendor-approval-table .content-table tbody tr {
        border: 1px solid #dddddd;
      }
      .vendor-approval-table .content-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
      }
      .vendor-approval-table .content-table tbody tr:last-of-type {
        border-bottom: 3px solid #009879;
      }
      .vendor-approval-table .content-table tbody tr td button {
        padding: 10px 20px;
        border: none;
        background-color: rgb(11, 173, 119);
        border-radius: 4px;
        font-size: 16px;
        color: white;
        font-weight: bold;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <div class="vendor-approval-table">
      <nav>
        <div class="nav">
          <a href="{% url 'admin_app:admin_page' %}">Home</a>
        </div>
      </nav>
      <table class="content-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Approval</th>
          </tr>
        </thead>
        <tbody>
          {% for i in vendor_object %}
          <tr>
            <td>{{i.vendor_name}}</td>
            <td>{{i.vendor_email}}</td>

            <form action="" method="post">
              {% csrf_token %}
              <td>
                <input type="text" name="idno" value="{{i.id}}" hidden />
                <button type="submit">Approve</button>
              </td>
            </form>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>

templates/feedback_by_user_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Feedback</title>

    <style>
      body {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }
      .feedback-by-user {
        background-color: darkslategray;
        height: 100vh;
        width: 100%;
        color: white;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
      }
      .feedback-by-user nav {
        position: fixed;
        top: 0;
      }
      .feedback-by-user nav .feedback-nav {
        width: 100vw;
        height: 80px;
        background: transparent;
        display: flex;
        align-items: center;
        justify-content: start;
      }
      .feedback-by-user nav a {
        color: white;
        margin-left: 10px;
        text-decoration: none;
        font-weight: bold;
        font-size: 16px;
      }
      .feedback-by-user form .container {
        padding: 40px;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
      }

      /* Full-width input fields */
      .feedback-by-user form .container input[type="text"] {
        width: 98%;
        padding: 15px;
        padding-bottom: 200px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
      }

      .feedback-by-user form .container input[type="text"]:focus {
        background-color: #ddd;
        outline: none;
      }

      .feedback-by-user form .container hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
      }

      .feedback-by-user form .container button {
        background-color: #04aa6d;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        font-size: 18px;
        width: 100%;
        font-weight: bold;
        opacity: 0.9;
      }
    </style>
  </head>
  <body>
    <div class="feedback-by-user">
      <nav>
        <div class="feedback-nav">
          <a href="{% url 'user_app:user_page' %}">Home Page</a>
        </div>
      </nav>
      <form action="" method="post">
        {% csrf_token %}
        <div class="container">
          <h2 style="margin-top: 8rem">Please submit a feedback</h2>
          <hr />

          <label><b>How was your experience with us?</b></label>
          <input
            type="text"
            placeholder="Your feedback goes here"
            name="feedback_of_user"
            required
            maxlength="300"
          />
          <button type="submit" class="submit-btn">Submit Feedback</button>
        </div>
      </form>
    </div>
  </body>
</html>

templates/order_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Order Page</title>

    <style>
      body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      .order-table-container {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
        height: 100vh;
        width: 100%;
        background-color: rgb(59, 56, 56);
      }
      .order-table-container nav {
        position: fixed;
        top: 0;
      }
      .order-table-container nav .orders {
        width: 100vw;
        height: 80px;
        background: rgb(228, 226, 226);
        display: flex;
        align-items: center;
        justify-content: start;
      }
      .order-table-container nav a {
        color: rgb(3, 10, 102);
        margin-left: 10px;
        text-decoration: none;
        font-weight: bold;
        font-size: 16px;
      }
      .order-table-container .flex-row {
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        text-align: start;
        padding-top: 2rem;
        border-bottom: 1px solid gray;
        text-align: center;
        margin-top: 5rem;
      }
      .order-table-container .flex-row span {
        border: 1px solid gray;
        height: auto;
      }

      .order-table-container .flex-row .order-item,
      .order-price,
      .order-date,
      .order-delete,
      .customer-name,
      .pre-order-date,
      .customer-train-number {
        font-size: 18px;
        margin-bottom: 2rem;
        color: rgb(171, 230, 185);
        font-weight: bold;
      }

      .order-table-container .flex-row .order-item-child,
      .order-price-child,
      .order-date-child,
      .pre-order-date-child,
      .order-delete-child,
      .customers,
      .customer-train-number-child {
        margin-top: 1rem;
        font-weight: normal;
        color: white;
      }
      .order-table-container
        .flex-row
        .order-item
        .order-item-child:first-child,
      .order-price-child:first-child,
      .order-date-child:first-child,
      .pre-order-date-child:first-child,
      .order-delete-child:first-child,
      .customers:first-child,
      .customer-train-number-child:first-child {
        margin-top: 2.5rem;
      }
    </style>
  </head>
  <body>
    <div class="order-table-container">
      <nav>
        <div class="orders">
          <a href="{% url 'user_app:user_page' %}">Home Page</a>
        </div>
      </nav>
      <div class="flex-row">
        <div class="customer-name">
          Train Number {% for i in orders %}
          <div class="customers">{{i.train_number}}</div>
          {% endfor %}
        </div>
        <span></span>

        <div class="customer-train-number">
          Customer Name {% for i in orders %}
          <div class="customer-train-number-child">{{i.customer_name}}</div>
          {% endfor %}
        </div>
        <span></span>

        <div class="order-item">
          Prouct {% for i in orders %}
          <div class="order-item-child">{{i.product_name}}</div>
          {% endfor %}
        </div>
        <span></span>

        <div class="order-price">
          Price {% for i in orders %}
          <div class="order-price-child">${{i.price}}</div>
          {% endfor %}
        </div>
        <span></span>

        <div class="order-date">
          Date {% for i in orders %}

          <div class="order-date-child">{{i.date}}</div>
          {% endfor %}
        </div>
        <span></span>

        <div class="pre-order-date">
          Pre Order Date {% for i in orders %}

          <div class="pre-order-date-child">{{i.pre_order_date}}</div>
          {% endfor %}
        </div>
        <span></span>

        <div class="order-delete">
          Remove {% for i in orders %}

          <div class="order-delete-child">
            <a href="{% url 'user_app:order_page_remove_item' i.id %}">🗑</a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/pnr_generator.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Available PNR</title>


  <style>
    body{
      padding: 0;
      margin: 0;
      box-sizing: border-box;
    }
    .pnr-rendering-page{
      height: 100vh;
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;

    }
    .pnr-rendering-page nav {
      position: fixed;
      top: 0;
    }
    .pnr-rendering-page nav .nav {
      width: 100vw;
      height: 80px;
      background: rgb(171, 171, 171);
      display: flex;
      align-items: center;
      justify-content: start;
    }
    .pnr-rendering-page nav a {
      color: rgb(3, 10, 102);
      margin-left: 10px;
      text-decoration: none;
      font-weight: bold;
      font-size: 16px;
      margin-right: 1rem;
    }
    .pnr-rendering-page .user-table .content-table tr td button{
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      background-color: red;
      margin: 4px;
    }
    .pnr-rendering-page .user-table .content-table tr td a button{
      cursor: pointer;
      text-decoration: none;
      color: white;
      font-weight: bold;
    }
  </style>
  
  
</head>

<body>

  <div class="pnr-rendering-page">
    <nav>
      <div class="nav">
        <a href="{% url 'user_app:user_page' %}">Back</a>
      </div>
    </nav>
    <div class="user-table">
      <table class="content-table" bgcolor="black" width="900" style="text-align: center;">
          <tr bgcolor="gray" style="color: white;" height="50">
            <th width="100">NO:</th>
            <th width="200">PNR NUMBER</th>
            <th width="200">Station</th>
          </tr>
          {% for i in pnr %}
          <tr bgcolor="lightgray" height="50">
            <td>{{forloop.counter}}</td>
            <td>{{i.pnr_number}}</td>
            <td>{{i.pnr_station}}</td>
          </tr>
          {% endfor %}
      </table>  
    </div>
</body>
</html>

templates/user_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>USER</title>

    <style>
      body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      .user-page-container {
        height: 100vh;
        width: 100%;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
        position: relative;
      }
      .user-page-container nav {
        position: fixed;
        top: 0;
      }
      .user-page-container nav .orders {
        width: 100vw;
        height: 80px;
        background: rgb(228, 226, 226);
        display: flex;
        align-items: center;
        justify-content: start;
        gap: 1rem;
      }
      .user-page-container nav a {
        color: rgb(3, 10, 102);
        margin-left: 10px;
        text-decoration: none;
        font-weight: bold;
        font-size: 16px;
      }
      .user-page-container .card-container {
        margin-top: 100px;
        padding: 20px;
        display: grid;
        grid-template-columns: repeat(5, 1fr);
        gap: 25px;
      }
      .user-page-container .card-container .cards {
        box-shadow: 0px 0px 14px rgba(0, 0, 0, 0.3);
        border-radius: 3px;
        display: flex;
        flex-direction: column;
        overflow: hidden;
        padding: 10px;
        word-wrap: break-word;
      }
      .user-page-container .card-container .cards img {
        width: 100%;
        height: 180px;
        margin-bottom: 10px;
      }
      .user-page-container .card-container .cards .card-details {
        display: flex;
        flex-direction: column;
        margin-bottom: 10px;
        font-weight: bold;
        gap: 5px;
      }
      .user-page-container .card-container .cards .buy-product {
        display: grid;
        grid-template-columns: repeat(1, 1fr);
        margin-bottom: 10px;
      }
      .user-page-container .card-container .cards .buy-product button {
        cursor: pointer;
        padding: 10px 20px;
      }
      .user-page-container .card-container .cards .buy-product .btn-buy {
        color: white;
        background: green;
        border-radius: 3px;
        border: none;
      }

      .user-page-container nav .orders input {
        padding: 10px 20px;
        margin-left: 5rem;
        outline: none;
        border-radius: 3px;
        font-size: 16px;
        border: none;
      }
      .user-page-container nav .orders button {
        padding: 11px;
        margin-left: 5px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
        background-color: white;
      }

      .user-page-container .no-item-found {
        text-align: center;
        font-size: 20px;
        font-weight: bold;
      }
      .user-page-container nav .words {
        position: relative;
        animation: move-words 16s linear infinite;
        font-size: 16px;
        font-weight: bold;
        color: rgb(31, 41, 185);
      }
      .user-page-container nav .width-words {
        position: absolute;
        bottom: -16px;
        right: 900px;
      }
      @keyframes move-words {
        0% {
          left: 300%;
        }
        100% {
          left: -330%;
        }
      }
    </style>
  </head>
  <body>
    <div class="user-page-container">
      <nav>
        <div class="orders">
          <a href="{% url 'user_app:order_page' %}">Orders</a>
          <a href="{% url 'user_app:display_pnr' %}">PNR</a>
          <a href="{% url 'user_app:login_page_user' %}">Log Out</a>

          <form action="" method="post">
            {% csrf_token %}
            <input
              type="text"
              name="search_category"
              class="search-category"
              placeholder="Your Favorite Category"
            />
            <button>🔎</button>
          </form>
          <form action="" method="post">
            {% csrf_token %}
            <input
              type="text"
              name="pnr_number_search"
              class="search-category"
              placeholder="Your PNR Number"
            />
            <button>🔎</button>
          </form>
          <button
            class="color"
            style="position: fixed; right: 20px"
            onclick="changeBackground()"
          >
            dark mode
          </button>
          <div class="width-words">
            <p class="words">
              TIP: If your station is current station you don't have to
              pre-order.
            </p>
          </div>
          {% for i in current_station %}
          <div style="position: absolute; right: 200px; color: red">
            Current Station: {{i.current_station}}
          </div>
          {% endfor %}
        </div>
      </nav>
      <div class="card-container">
        {% for i in food_items %}
        <div class="cards">
          <img src="{{i.food_image.url}}" alt="/" />
          <div class="card-details">
            <div>
              Name:
              <span style="color: red" class="red-color-span"
                >{{i.food_name}}</span
              >
            </div>
            <div>Category: {{i.food_category}}</div>
            <div>
              Rate:
              <span
                style="text-decoration: line-through; color: black"
                class="old-money-span"
                >$5000</span
              ><span
                class="new-money-span"
                style="color: rgb(17, 136, 17); margin-left: 5px"
                >${{i.food_price}}</span
              >
            </div>
            <div>Resturant Name: {{i.resturant_name}}</div>
            <div hidden>Station Name: {{i.station_name}}</div>
          </div>
          <form action="{% url 'user_app:order_page' %}" method="post">
            <div class="buy-product">
              {% csrf_token %}
              <button class="btn-buy" type="submit">BUY NOW</button>
            </div>
            <input type="text" hidden value="{{i.id}}" name="idno" />
            <input
              type="text"
              hidden
              value="{{i.food_name}}"
              name="food_name"
            />
            <input
              type="text"
              hidden
              value="{{i.food_price}}"
              name="food_price"
            />
          </form>
        </div>
        {% endfor %}
      </div>
      <h2 style="margin-left: 40%">{{msg}}</h2>
    </div>

    <script>
      function changeBackground() {
        var body = document.body;
        var cards = document.querySelectorAll(".cards");
        var redColorSpan = document.querySelectorAll(".red-color-span");
        var oldMoneySpan = document.querySelectorAll(".old-money-span");
        var newMoneySpan = document.querySelectorAll(".new-money-span");

        if (body.classList.contains("dark-mode")) {
          // Change to normal mode
          body.classList.remove("dark-mode");
          body.style.backgroundColor = "#fff";
          body.style.color = "black";

          redColorSpan.forEach(function (item) {
            item.style.color = "red";
          });

          oldMoneySpan.forEach(function (item) {
            item.style.color = "black";
          });

          newMoneySpan.forEach(function (item) {
            item.style.color = "green";
          });

          document.querySelector(".color").innerHTML = "dark mode";
        } else {
          // Change to dark mode
          body.classList.add("dark-mode");
          body.style.backgroundColor = "#333";
          body.style.color = "#fff";

          redColorSpan.forEach(function (item) {
            item.style.color = "yellow";
          });

          oldMoneySpan.forEach(function (item) {
            item.style.color = "red";
          });

          newMoneySpan.forEach(function (item) {
            item.style.color = "yellow";
          });

          document.querySelector(".color").innerHTML = "light mode";
        }
      }
    </script>
  </body>
</html>

templates/vendor_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SELLER</title>

    <style>
      body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      .vendor-page-container {
        height: 100vh;
        width: 100%;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
        position: relative;
      }
      .vendor-page-container nav {
        position: fixed;
        top: 0;
      }
      .vendor-page-container nav .add-food {
        width: 100vw;
        height: 80px;
        background: rgb(228, 226, 226);
        display: flex;
        align-items: center;
        justify-content: start;
      }
      .vendor-page-container nav a {
        color: rgb(3, 10, 102);
        margin-left: 10px;
        text-decoration: none;
        font-weight: bold;
        font-size: 16px;
        margin-right: 1rem;
      }
      .vendor-page-container .card-container {
        margin-top: 100px;
        padding: 20px;
        display: grid;
        grid-template-columns: repeat(5, 1fr);
        gap: 25px;
      }
      .vendor-page-container .card-container .cards {
        box-shadow: 0px 0px 20px rgb(180, 179, 179);
        border-radius: 3px;
        display: flex;
        flex-direction: column;
        overflow: hidden;
        padding: 10px;
        word-wrap: break-word;
      }
      .vendor-page-container .card-container .cards img {
        width: 100%;
        height: 180px;
        margin-bottom: 10px;
      }
      .vendor-page-container .card-container .cards .card-details {
        display: flex;
        flex-direction: column;
        margin-bottom: 10px;
        font-weight: bold;
        gap: 5px;
      }
      .vendor-page-container .card-container .cards .modify-product {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
      }
      .vendor-page-container .card-container .cards .modify-product button {
        cursor: pointer;
        padding: 10px 20px;
      }
      .vendor-page-container
        .card-container
        .cards
        .modify-product
        .btn-delete {
        background: red;
        border-radius: 3px;
        border: none;
      }
      .vendor-page-container
        .card-container
        .cards
        .modify-product
        .btn-update {
        background: green;
        border-radius: 3px;
        border: none;
      }
      .vendor-page-container .card-container .cards .modify-product button a {
        text-decoration: none;
        color: white;
        font-size: 14px;
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <div class="vendor-page-container">
      <nav>
        <div class="add-food">
          <a href="{% url 'vendor_app:add_food' %}">Add Food</a>
          <a href="{% url 'vendor_app:order_page_vendor' %}">Orders</a>
          <a href="{% url 'vendor_app:login_page' %}">Log Out</a>
        </div>
      </nav>
      <div class="card-container">
        {% for i in food_items %}
        <div class="cards">
          <img src="{{i.food_image.url}}" alt="/" />
          <div class="card-details">
            <div>Name: <span style="color: red">{{i.food_name}}</span></div>
            <div>Category: {{i.food_category}}</div>
            <div>
              Rate:
              <span style="margin-left: 5px">${{i.food_price}}</span>
            </div>
              <div>Resturant Name: {{i.resturant_name}}</div>
              <div>Station Name: {{i.station_name}}</div>
          </div>
          <div class="modify-product">
            <button class="btn-delete">
              <a href="{% url 'vendor_app:delete_product' i.id %}">DELETE</a>
            </button>
            <button class="btn-update">
              <a href="{% url 'vendor_app:update_food' i.id %}">UPDATE</a>
            </button>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </body>
</html>